### ISSUE TITLE
Компонентность 

### ISSUE THREAD

**Issue by DmitrijMTP** [nicoproject/toxin-reworked#8]
Сейчас в проекте отдельно лежать pug файлы, отдельно стили и т.д. Можешь почитать о структуре проектов по БЭМ [тут](https://ru.bem.info/methodology/filestructure/).
Каждый БЭМ блок должен содержать все нужные файлы для него, т.е. он должен быть независимым. Нужно переделать.

**Comment by nicoproject** [comment]
1. Разнес файлы по компонентам 
2. Для импортов в scss и js файлах использовал webpack resolve alias ~ 

Сам комит номинальный (там только папка переименована), я перепутал и начал делать #8 первым, зацепил 6 и 7 и получилось, что в комитах намешаны правки для разных issues.
Проверил запуск dev, успешно
